/***************************************************************************//**
* \file cyhal_triggers_mxs28playermcuss.h
*
* \brief
* MXS28PLAYERMCUSS family HAL triggers header
*
* \note
* Generator version: 1.6.0.512
*
********************************************************************************
* \copyright
* Copyright 2016-2021 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#ifndef _CYHAL_TRIGGERS_MXS28PLAYERMCUSS_H_
#define _CYHAL_TRIGGERS_MXS28PLAYERMCUSS_H_

/**
 * \addtogroup group_hal_impl_triggers_mxs28playermcuss MXS28PLAYERMCUSS
 * \ingroup group_hal_impl_triggers
 * \{
 * Trigger connections for mxs28playermcuss
 */

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/** \cond INTERNAL */
/** @brief Name of each input trigger. */
typedef enum
{
    _CYHAL_TRIGGER_CPUSS_ZERO = 0, //!< cpuss.zero
    _CYHAL_TRIGGER_ADCCOMP_TR_CIC = 1, //!< adccomp.tr_cic
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP1 = 2, //!< adccomp.tr_lpcomp1
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP2 = 3, //!< adccomp.tr_lpcomp2
    _CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_FROM_WLAN_OUT = 4, //!< connbridge.tcpwm_trig_from_wlan_out
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT0 = 5, //!< cpuss.cti_tr_out[0]
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT1 = 6, //!< cpuss.cti_tr_out[1]
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT0 = 7, //!< cpuss.dmac0_tr_out[0]
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT1 = 8, //!< cpuss.dmac0_tr_out[1]
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT0 = 9, //!< cpuss.dmac1_tr_out[0]
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT1 = 10, //!< cpuss.dmac1_tr_out[1]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0 = 11, //!< cpuss.dw0_tr_out[0]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1 = 12, //!< cpuss.dw0_tr_out[1]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2 = 13, //!< cpuss.dw0_tr_out[2]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3 = 14, //!< cpuss.dw0_tr_out[3]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4 = 15, //!< cpuss.dw0_tr_out[4]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5 = 16, //!< cpuss.dw0_tr_out[5]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6 = 17, //!< cpuss.dw0_tr_out[6]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7 = 18, //!< cpuss.dw0_tr_out[7]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT8 = 19, //!< cpuss.dw0_tr_out[8]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT9 = 20, //!< cpuss.dw0_tr_out[9]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT10 = 21, //!< cpuss.dw0_tr_out[10]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT11 = 22, //!< cpuss.dw0_tr_out[11]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT12 = 23, //!< cpuss.dw0_tr_out[12]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT13 = 24, //!< cpuss.dw0_tr_out[13]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT14 = 25, //!< cpuss.dw0_tr_out[14]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT15 = 26, //!< cpuss.dw0_tr_out[15]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT16 = 27, //!< cpuss.dw0_tr_out[16]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT17 = 28, //!< cpuss.dw0_tr_out[17]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT18 = 29, //!< cpuss.dw0_tr_out[18]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT19 = 30, //!< cpuss.dw0_tr_out[19]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT20 = 31, //!< cpuss.dw0_tr_out[20]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT21 = 32, //!< cpuss.dw0_tr_out[21]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT22 = 33, //!< cpuss.dw0_tr_out[22]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT23 = 34, //!< cpuss.dw0_tr_out[23]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT24 = 35, //!< cpuss.dw0_tr_out[24]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT25 = 36, //!< cpuss.dw0_tr_out[25]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT26 = 37, //!< cpuss.dw0_tr_out[26]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT27 = 38, //!< cpuss.dw0_tr_out[27]
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT28 = 39, //!< cpuss.dw0_tr_out[28]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0 = 40, //!< cpuss.dw1_tr_out[0]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1 = 41, //!< cpuss.dw1_tr_out[1]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2 = 42, //!< cpuss.dw1_tr_out[2]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3 = 43, //!< cpuss.dw1_tr_out[3]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4 = 44, //!< cpuss.dw1_tr_out[4]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5 = 45, //!< cpuss.dw1_tr_out[5]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6 = 46, //!< cpuss.dw1_tr_out[6]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7 = 47, //!< cpuss.dw1_tr_out[7]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT8 = 48, //!< cpuss.dw1_tr_out[8]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT9 = 49, //!< cpuss.dw1_tr_out[9]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT10 = 50, //!< cpuss.dw1_tr_out[10]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT11 = 51, //!< cpuss.dw1_tr_out[11]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT12 = 52, //!< cpuss.dw1_tr_out[12]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT13 = 53, //!< cpuss.dw1_tr_out[13]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT14 = 54, //!< cpuss.dw1_tr_out[14]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT15 = 55, //!< cpuss.dw1_tr_out[15]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT16 = 56, //!< cpuss.dw1_tr_out[16]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT17 = 57, //!< cpuss.dw1_tr_out[17]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT18 = 58, //!< cpuss.dw1_tr_out[18]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT19 = 59, //!< cpuss.dw1_tr_out[19]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT20 = 60, //!< cpuss.dw1_tr_out[20]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT21 = 61, //!< cpuss.dw1_tr_out[21]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT22 = 62, //!< cpuss.dw1_tr_out[22]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT23 = 63, //!< cpuss.dw1_tr_out[23]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT24 = 64, //!< cpuss.dw1_tr_out[24]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT25 = 65, //!< cpuss.dw1_tr_out[25]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT26 = 66, //!< cpuss.dw1_tr_out[26]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT27 = 67, //!< cpuss.dw1_tr_out[27]
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT28 = 68, //!< cpuss.dw1_tr_out[28]
    _CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT = 69, //!< eth[0].eth_tsu_timer_cmp_val_out
    _CYHAL_TRIGGER_I3C_TR_RX_REQ = 70, //!< i3c.tr_rx_req
    _CYHAL_TRIGGER_I3C_TR_TX_REQ = 71, //!< i3c.tr_tx_req
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0 = 72, //!< ioss.peri_tr_io_input_in[0]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1 = 73, //!< ioss.peri_tr_io_input_in[1]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2 = 74, //!< ioss.peri_tr_io_input_in[2]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3 = 75, //!< ioss.peri_tr_io_input_in[3]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4 = 76, //!< ioss.peri_tr_io_input_in[4]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5 = 77, //!< ioss.peri_tr_io_input_in[5]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6 = 78, //!< ioss.peri_tr_io_input_in[6]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7 = 79, //!< ioss.peri_tr_io_input_in[7]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8 = 80, //!< ioss.peri_tr_io_input_in[8]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9 = 81, //!< ioss.peri_tr_io_input_in[9]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10 = 82, //!< ioss.peri_tr_io_input_in[10]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11 = 83, //!< ioss.peri_tr_io_input_in[11]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12 = 84, //!< ioss.peri_tr_io_input_in[12]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13 = 85, //!< ioss.peri_tr_io_input_in[13]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14 = 86, //!< ioss.peri_tr_io_input_in[14]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15 = 87, //!< ioss.peri_tr_io_input_in[15]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16 = 88, //!< ioss.peri_tr_io_input_in[16]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17 = 89, //!< ioss.peri_tr_io_input_in[17]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18 = 90, //!< ioss.peri_tr_io_input_in[18]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19 = 91, //!< ioss.peri_tr_io_input_in[19]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20 = 92, //!< ioss.peri_tr_io_input_in[20]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21 = 93, //!< ioss.peri_tr_io_input_in[21]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22 = 94, //!< ioss.peri_tr_io_input_in[22]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23 = 95, //!< ioss.peri_tr_io_input_in[23]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24 = 96, //!< ioss.peri_tr_io_input_in[24]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25 = 97, //!< ioss.peri_tr_io_input_in[25]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26 = 98, //!< ioss.peri_tr_io_input_in[26]
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27 = 99, //!< ioss.peri_tr_io_input_in[27]
    _CYHAL_TRIGGER_PDM_TR_RX_REQ_ALL = 100, //!< pdm.tr_rx_req_all
    _CYHAL_TRIGGER_PDM_TR_RX_REQ0 = 101, //!< pdm.tr_rx_req[0]
    _CYHAL_TRIGGER_PDM_TR_RX_REQ1 = 102, //!< pdm.tr_rx_req[1]
    _CYHAL_TRIGGER_PDM_TR_RX_REQ2 = 103, //!< pdm.tr_rx_req[2]
    _CYHAL_TRIGGER_PDM_TR_RX_REQ3 = 104, //!< pdm.tr_rx_req[3]
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED = 105, //!< scb[0].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED = 106, //!< scb[1].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED = 107, //!< scb[2].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED = 108, //!< scb[3].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED = 109, //!< scb[4].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED = 110, //!< scb[5].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB6_TR_I2C_SCL_FILTERED = 111, //!< scb[6].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB7_TR_I2C_SCL_FILTERED = 112, //!< scb[7].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ = 113, //!< scb[0].tr_rx_req
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ = 114, //!< scb[1].tr_rx_req
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ = 115, //!< scb[2].tr_rx_req
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ = 116, //!< scb[3].tr_rx_req
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ = 117, //!< scb[4].tr_rx_req
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ = 118, //!< scb[5].tr_rx_req
    _CYHAL_TRIGGER_SCB6_TR_RX_REQ = 119, //!< scb[6].tr_rx_req
    _CYHAL_TRIGGER_SCB7_TR_RX_REQ = 120, //!< scb[7].tr_rx_req
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ = 121, //!< scb[0].tr_tx_req
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ = 122, //!< scb[1].tr_tx_req
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ = 123, //!< scb[2].tr_tx_req
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ = 124, //!< scb[3].tr_tx_req
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ = 125, //!< scb[4].tr_tx_req
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ = 126, //!< scb[5].tr_tx_req
    _CYHAL_TRIGGER_SCB6_TR_TX_REQ = 127, //!< scb[6].tr_tx_req
    _CYHAL_TRIGGER_SCB7_TR_TX_REQ = 128, //!< scb[7].tr_tx_req
    _CYHAL_TRIGGER_SMIF_TR_RX_REQ = 129, //!< smif.tr_rx_req
    _CYHAL_TRIGGER_SMIF_TR_TX_REQ = 130, //!< smif.tr_tx_req
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0 = 131, //!< tcpwm[0].tr_cc_match[0]
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1 = 132, //!< tcpwm[0].tr_cc_match[1]
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2 = 133, //!< tcpwm[0].tr_cc_match[2]
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3 = 134, //!< tcpwm[0].tr_cc_match[3]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0 = 135, //!< tcpwm[1].tr_cc_match[0]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1 = 136, //!< tcpwm[1].tr_cc_match[1]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2 = 137, //!< tcpwm[1].tr_cc_match[2]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3 = 138, //!< tcpwm[1].tr_cc_match[3]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4 = 139, //!< tcpwm[1].tr_cc_match[4]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5 = 140, //!< tcpwm[1].tr_cc_match[5]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6 = 141, //!< tcpwm[1].tr_cc_match[6]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7 = 142, //!< tcpwm[1].tr_cc_match[7]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8 = 143, //!< tcpwm[1].tr_cc_match[8]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9 = 144, //!< tcpwm[1].tr_cc_match[9]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10 = 145, //!< tcpwm[1].tr_cc_match[10]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11 = 146, //!< tcpwm[1].tr_cc_match[11]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12 = 147, //!< tcpwm[1].tr_cc_match[12]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13 = 148, //!< tcpwm[1].tr_cc_match[13]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14 = 149, //!< tcpwm[1].tr_cc_match[14]
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15 = 150, //!< tcpwm[1].tr_cc_match[15]
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0 = 151, //!< tcpwm[0].tr_overflow[0]
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1 = 152, //!< tcpwm[0].tr_overflow[1]
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2 = 153, //!< tcpwm[0].tr_overflow[2]
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3 = 154, //!< tcpwm[0].tr_overflow[3]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0 = 155, //!< tcpwm[1].tr_overflow[0]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1 = 156, //!< tcpwm[1].tr_overflow[1]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2 = 157, //!< tcpwm[1].tr_overflow[2]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3 = 158, //!< tcpwm[1].tr_overflow[3]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4 = 159, //!< tcpwm[1].tr_overflow[4]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5 = 160, //!< tcpwm[1].tr_overflow[5]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6 = 161, //!< tcpwm[1].tr_overflow[6]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7 = 162, //!< tcpwm[1].tr_overflow[7]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8 = 163, //!< tcpwm[1].tr_overflow[8]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9 = 164, //!< tcpwm[1].tr_overflow[9]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10 = 165, //!< tcpwm[1].tr_overflow[10]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11 = 166, //!< tcpwm[1].tr_overflow[11]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12 = 167, //!< tcpwm[1].tr_overflow[12]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13 = 168, //!< tcpwm[1].tr_overflow[13]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14 = 169, //!< tcpwm[1].tr_overflow[14]
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15 = 170, //!< tcpwm[1].tr_overflow[15]
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0 = 171, //!< tcpwm[0].tr_underflow[0]
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1 = 172, //!< tcpwm[0].tr_underflow[1]
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2 = 173, //!< tcpwm[0].tr_underflow[2]
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3 = 174, //!< tcpwm[0].tr_underflow[3]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0 = 175, //!< tcpwm[1].tr_underflow[0]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1 = 176, //!< tcpwm[1].tr_underflow[1]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2 = 177, //!< tcpwm[1].tr_underflow[2]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3 = 178, //!< tcpwm[1].tr_underflow[3]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4 = 179, //!< tcpwm[1].tr_underflow[4]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5 = 180, //!< tcpwm[1].tr_underflow[5]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6 = 181, //!< tcpwm[1].tr_underflow[6]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7 = 182, //!< tcpwm[1].tr_underflow[7]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8 = 183, //!< tcpwm[1].tr_underflow[8]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9 = 184, //!< tcpwm[1].tr_underflow[9]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10 = 185, //!< tcpwm[1].tr_underflow[10]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11 = 186, //!< tcpwm[1].tr_underflow[11]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12 = 187, //!< tcpwm[1].tr_underflow[12]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13 = 188, //!< tcpwm[1].tr_underflow[13]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14 = 189, //!< tcpwm[1].tr_underflow[14]
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15 = 190, //!< tcpwm[1].tr_underflow[15]
    _CYHAL_TRIGGER_TDM_TR_RX_REQ0 = 191, //!< tdm.tr_rx_req[0]
    _CYHAL_TRIGGER_TDM_TR_RX_REQ1 = 192, //!< tdm.tr_rx_req[1]
    _CYHAL_TRIGGER_TDM_TR_TX_REQ0 = 193, //!< tdm.tr_tx_req[0]
    _CYHAL_TRIGGER_TDM_TR_TX_REQ1 = 194, //!< tdm.tr_tx_req[1]
} _cyhal_trigger_source_mxs28playermcuss_t;

/** Typedef for internal device family specific trigger source to generic trigger source */
typedef _cyhal_trigger_source_mxs28playermcuss_t cyhal_internal_source_t;

/** @brief Get a public source signal type (cyhal_trigger_source_mxs28playermcuss_t) given an internal source signal and signal type */
#define _CYHAL_TRIGGER_CREATE_SOURCE(src, type)    ((src) << 1 | (type))
/** @brief Get an internal source signal (_cyhal_trigger_source_mxs28playermcuss_t) given a public source signal. */
#define _CYHAL_TRIGGER_GET_SOURCE_SIGNAL(src)      ((cyhal_internal_source_t)((src) >> 1))
/** @brief Get the signal type (cyhal_signal_type_t) given a public source signal. */
#define _CYHAL_TRIGGER_GET_SOURCE_TYPE(src)        ((cyhal_signal_type_t)((src) & 1))
/** \endcond */

/** @brief Name of each input trigger. */
typedef enum
{
    CYHAL_TRIGGER_CPUSS_ZERO_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_ZERO, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.zero
    CYHAL_TRIGGER_CPUSS_ZERO_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_ZERO, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.zero
    CYHAL_TRIGGER_ADCCOMP_TR_CIC = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_ADCCOMP_TR_CIC, CYHAL_SIGNAL_TYPE_LEVEL), //!< adccomp.tr_cic
    CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP1, CYHAL_SIGNAL_TYPE_LEVEL), //!< adccomp.tr_lpcomp1
    CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP2, CYHAL_SIGNAL_TYPE_LEVEL), //!< adccomp.tr_lpcomp2
    CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_FROM_WLAN_OUT = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_FROM_WLAN_OUT, CYHAL_SIGNAL_TYPE_LEVEL), //!< connbridge.tcpwm_trig_from_wlan_out
    CYHAL_TRIGGER_CPUSS_CTI_TR_OUT0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_CTI_TR_OUT0, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.cti_tr_out[0]
    CYHAL_TRIGGER_CPUSS_CTI_TR_OUT1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_CTI_TR_OUT1, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.cti_tr_out[1]
    CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT0, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac0_tr_out[0]
    CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT1, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac0_tr_out[1]
    CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT0, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac1_tr_out[0]
    CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT1, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac1_tr_out[1]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[0]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[1]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[2]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[3]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[4]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[5]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[6]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[7]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT8 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT8, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[8]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT9 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT9, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[9]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT10 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT10, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[10]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT11 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT11, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[11]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT12 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT12, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[12]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT13 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT13, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[13]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT14 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT14, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[14]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT15 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT15, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[15]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT16 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT16, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[16]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT17 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT17, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[17]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT18 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT18, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[18]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT19 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT19, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[19]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT20 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT20, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[20]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT21 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT21, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[21]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT22 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT22, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[22]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT23 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT23, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[23]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT24 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT24, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[24]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT25 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT25, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[25]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT26 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT26, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[26]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT27 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT27, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[27]
    CYHAL_TRIGGER_CPUSS_DW0_TR_OUT28 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW0_TR_OUT28, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw0_tr_out[28]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[0]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[1]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[2]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[3]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[4]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[5]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[6]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[7]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT8 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT8, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[8]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT9 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT9, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[9]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT10 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT10, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[10]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT11 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT11, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[11]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT12 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT12, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[12]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT13 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT13, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[13]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT14 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT14, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[14]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT15 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT15, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[15]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT16 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT16, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[16]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT17 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT17, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[17]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT18 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT18, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[18]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT19 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT19, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[19]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT20 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT20, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[20]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT21 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT21, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[21]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT22 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT22, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[22]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT23 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT23, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[23]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT24 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT24, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[24]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT25 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT25, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[25]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT26 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT26, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[26]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT27 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT27, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[27]
    CYHAL_TRIGGER_CPUSS_DW1_TR_OUT28 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DW1_TR_OUT28, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dw1_tr_out[28]
    CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT, CYHAL_SIGNAL_TYPE_EDGE), //!< eth[0].eth_tsu_timer_cmp_val_out
    CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT, CYHAL_SIGNAL_TYPE_LEVEL), //!< eth[0].eth_tsu_timer_cmp_val_out
    CYHAL_TRIGGER_I3C_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_I3C_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< i3c.tr_rx_req
    CYHAL_TRIGGER_I3C_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_I3C_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< i3c.tr_tx_req
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[0]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[0]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[1]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[1]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[2]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[2]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[3]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[3]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[4]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[4]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[5]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[5]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[6]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[6]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[7]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[7]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[8]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[8]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[9]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[9]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[10]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[10]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[11]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[11]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[12]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[12]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[13]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[13]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[14]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[14]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[15]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[15]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[16]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[16]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[17]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[17]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[18]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[18]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[19]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[19]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[20]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[20]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[21]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[21]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[22]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[22]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[23]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[23]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[24]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[24]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[25]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[25]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[26]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[26]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27, CYHAL_SIGNAL_TYPE_EDGE), //!< ioss.peri_tr_io_input_in[27]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27, CYHAL_SIGNAL_TYPE_LEVEL), //!< ioss.peri_tr_io_input_in[27]
    CYHAL_TRIGGER_PDM_TR_RX_REQ_ALL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PDM_TR_RX_REQ_ALL, CYHAL_SIGNAL_TYPE_LEVEL), //!< pdm.tr_rx_req_all
    CYHAL_TRIGGER_PDM_TR_RX_REQ0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PDM_TR_RX_REQ0, CYHAL_SIGNAL_TYPE_LEVEL), //!< pdm.tr_rx_req[0]
    CYHAL_TRIGGER_PDM_TR_RX_REQ1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PDM_TR_RX_REQ1, CYHAL_SIGNAL_TYPE_LEVEL), //!< pdm.tr_rx_req[1]
    CYHAL_TRIGGER_PDM_TR_RX_REQ2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PDM_TR_RX_REQ2, CYHAL_SIGNAL_TYPE_LEVEL), //!< pdm.tr_rx_req[2]
    CYHAL_TRIGGER_PDM_TR_RX_REQ3 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PDM_TR_RX_REQ3, CYHAL_SIGNAL_TYPE_LEVEL), //!< pdm.tr_rx_req[3]
    CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[0].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[1].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[2].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[3].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[4].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[5].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB6_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB6_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[6].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB7_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB7_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[7].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB0_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB0_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[0].tr_rx_req
    CYHAL_TRIGGER_SCB1_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB1_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[1].tr_rx_req
    CYHAL_TRIGGER_SCB2_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB2_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[2].tr_rx_req
    CYHAL_TRIGGER_SCB3_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB3_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[3].tr_rx_req
    CYHAL_TRIGGER_SCB4_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB4_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[4].tr_rx_req
    CYHAL_TRIGGER_SCB5_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB5_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[5].tr_rx_req
    CYHAL_TRIGGER_SCB6_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB6_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[6].tr_rx_req
    CYHAL_TRIGGER_SCB7_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB7_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[7].tr_rx_req
    CYHAL_TRIGGER_SCB0_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB0_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[0].tr_tx_req
    CYHAL_TRIGGER_SCB1_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB1_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[1].tr_tx_req
    CYHAL_TRIGGER_SCB2_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB2_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[2].tr_tx_req
    CYHAL_TRIGGER_SCB3_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB3_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[3].tr_tx_req
    CYHAL_TRIGGER_SCB4_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB4_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[4].tr_tx_req
    CYHAL_TRIGGER_SCB5_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB5_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[5].tr_tx_req
    CYHAL_TRIGGER_SCB6_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB6_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[6].tr_tx_req
    CYHAL_TRIGGER_SCB7_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB7_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[7].tr_tx_req
    CYHAL_TRIGGER_SMIF_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SMIF_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< smif.tr_rx_req
    CYHAL_TRIGGER_SMIF_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SMIF_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< smif.tr_tx_req
    CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_cc_match[0]
    CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_cc_match[1]
    CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_cc_match[2]
    CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_cc_match[3]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[0]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[1]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[2]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[3]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[4]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[5]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[6]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[7]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[8]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[9]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[10]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[11]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[12]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[13]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[14]
    CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_cc_match[15]
    CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_overflow[0]
    CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_overflow[1]
    CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_overflow[2]
    CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_overflow[3]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[0]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[1]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[2]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[3]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[4]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[5]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[6]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[7]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[8]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[9]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[10]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[11]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[12]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[13]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[14]
    CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_overflow[15]
    CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_underflow[0]
    CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_underflow[1]
    CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_underflow[2]
    CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[0].tr_underflow[3]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[0]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[1]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[2]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[3]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[4]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[5]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[6]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[7]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[8]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[9]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[10]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[11]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[12]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[13]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[14]
    CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm[1].tr_underflow[15]
    CYHAL_TRIGGER_TDM_TR_RX_REQ0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TDM_TR_RX_REQ0, CYHAL_SIGNAL_TYPE_LEVEL), //!< tdm.tr_rx_req[0]
    CYHAL_TRIGGER_TDM_TR_RX_REQ1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TDM_TR_RX_REQ1, CYHAL_SIGNAL_TYPE_LEVEL), //!< tdm.tr_rx_req[1]
    CYHAL_TRIGGER_TDM_TR_TX_REQ0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TDM_TR_TX_REQ0, CYHAL_SIGNAL_TYPE_LEVEL), //!< tdm.tr_tx_req[0]
    CYHAL_TRIGGER_TDM_TR_TX_REQ1 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TDM_TR_TX_REQ1, CYHAL_SIGNAL_TYPE_LEVEL), //!< tdm.tr_tx_req[1]
} cyhal_trigger_source_mxs28playermcuss_t;

/** Typedef from device family specific trigger source to generic trigger source */
typedef cyhal_trigger_source_mxs28playermcuss_t cyhal_source_t;

/** Deprecated defines for signals that can be either level or edge. */
#define CYHAL_TRIGGER_CPUSS_ZERO (CYHAL_TRIGGER_CPUSS_ZERO_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT (CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27 (CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.

/** @brief Name of each output trigger. */
typedef enum
{
    CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_TO_WLAN_IN = 0, //!< TCPWM to WLAN through connbridge - connbridge.tcpwm_trig_to_wlan_in
    CYHAL_TRIGGER_CPUSS_CTI_TR_IN0 = 1, //!< CPUSS Debug and Profiler trigger multiplexer - cpuss.cti_tr_in[0]
    CYHAL_TRIGGER_CPUSS_CTI_TR_IN1 = 2, //!< CPUSS Debug and Profiler trigger multiplexer - cpuss.cti_tr_in[1]
    CYHAL_TRIGGER_CPUSS_DMAC0_TR_IN0 = 3, //!< MDMA trigger multiplexer - cpuss.dmac0_tr_in[0]
    CYHAL_TRIGGER_CPUSS_DMAC0_TR_IN1 = 4, //!< MDMA trigger multiplexer - cpuss.dmac0_tr_in[1]
    CYHAL_TRIGGER_CPUSS_DMAC1_TR_IN0 = 5, //!< MDMA trigger multiplexer - cpuss.dmac1_tr_in[0]
    CYHAL_TRIGGER_CPUSS_DMAC1_TR_IN1 = 6, //!< MDMA trigger multiplexer - cpuss.dmac1_tr_in[1]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN0 = 7, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[0]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN1 = 8, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[1]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN2 = 9, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[2]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN3 = 10, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[3]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN4 = 11, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[4]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN5 = 12, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[5]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN6 = 13, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[6]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN7 = 14, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[7]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN8 = 15, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[8]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN9 = 16, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[9]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN10 = 17, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[10]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN11 = 18, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[11]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN12 = 19, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[12]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN13 = 20, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[13]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN14 = 21, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[14]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN15 = 22, //!< P-DMA0 trigger multiplexer - cpuss.dw0_tr_in[15]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN16 = 23, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[16]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN17 = 24, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[17]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN18 = 25, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[18]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN19 = 26, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[19]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN20 = 27, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[20]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN21 = 28, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[21]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN22 = 29, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[22]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN23 = 30, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[23]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN24 = 31, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[24]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN25 = 32, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[25]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN26 = 33, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[26]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN27 = 34, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[27]
    CYHAL_TRIGGER_CPUSS_DW0_TR_IN28 = 35, //!< SCB DW0 Triggers - cpuss.dw0_tr_in[28]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN0 = 36, //!< P-DMA1 trigger multiplexer - cpuss.dw1_tr_in[0]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN1 = 37, //!< P-DMA1 trigger multiplexer - cpuss.dw1_tr_in[1]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN2 = 38, //!< P-DMA1 trigger multiplexer - cpuss.dw1_tr_in[2]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN3 = 39, //!< P-DMA1 trigger multiplexer - cpuss.dw1_tr_in[3]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN4 = 40, //!< P-DMA1 trigger multiplexer - cpuss.dw1_tr_in[4]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN5 = 41, //!< P-DMA1 trigger multiplexer - cpuss.dw1_tr_in[5]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN6 = 42, //!< P-DMA1 trigger multiplexer - cpuss.dw1_tr_in[6]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN7 = 43, //!< P-DMA1 trigger multiplexer - cpuss.dw1_tr_in[7]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN8 = 44, //!< SCB PDMA1 Triggers - cpuss.dw1_tr_in[8]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN9 = 45, //!< SCB PDMA1 Triggers - cpuss.dw1_tr_in[9]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN10 = 46, //!< SCB PDMA1 Triggers - cpuss.dw1_tr_in[10]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN11 = 47, //!< SCB PDMA1 Triggers - cpuss.dw1_tr_in[11]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN12 = 48, //!< SMIF to PDMA1 direct connect - cpuss.dw1_tr_in[12]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN13 = 49, //!< SMIF to PDMA1 direct connect - cpuss.dw1_tr_in[13]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN14 = 50, //!< AUDIOSS PDMA1 triggers (I2S & PDM) - cpuss.dw1_tr_in[14]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN15 = 51, //!< AUDIOSS PDMA1 triggers (I2S & PDM) - cpuss.dw1_tr_in[15]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN16 = 52, //!< AUDIOSS PDMA1 triggers (I2S & PDM) - cpuss.dw1_tr_in[16]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN17 = 53, //!< AUDIOSS PDMA1 triggers (I2S & PDM) - cpuss.dw1_tr_in[17]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN18 = 54, //!< AUDIOSS PDMA1 triggers (I2S & PDM) - cpuss.dw1_tr_in[18]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN19 = 55, //!< AUDIOSS PDMA1 triggers (I2S & PDM) - cpuss.dw1_tr_in[19]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN20 = 56, //!< Reserved PDMA1 triggers (ETH SDIO Device) - cpuss.dw1_tr_in[20]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN21 = 57, //!< Reserved PDMA1 triggers (ETH SDIO Device) - cpuss.dw1_tr_in[21]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN22 = 58, //!< Reserved PDMA1 triggers (ETH SDIO Device) - cpuss.dw1_tr_in[22]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN23 = 59, //!< Reserved PDMA1 triggers (ETH SDIO Device) - cpuss.dw1_tr_in[23]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN24 = 60, //!< Reserved PDMA1 triggers (ETH SDIO Device) - cpuss.dw1_tr_in[24]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN25 = 61, //!< Reserved PDMA1 triggers (ETH SDIO Device) - cpuss.dw1_tr_in[25]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN26 = 62, //!< Reserved PDMA1 triggers (ETH SDIO Device) - cpuss.dw1_tr_in[26]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN27 = 63, //!< Reserved PDMA1 triggers (ETH SDIO Device) - cpuss.dw1_tr_in[27]
    CYHAL_TRIGGER_CPUSS_DW1_TR_IN28 = 64, //!< Reserved PDMA1 triggers (ETH SDIO Device) - cpuss.dw1_tr_in[28]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT0 = 65, //!< HSIOM trigger multiplexer - ioss.peri_tr_io_output_out[0]
    CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT1 = 66, //!< HSIOM trigger multiplexer - ioss.peri_tr_io_output_out[1]
    CYHAL_TRIGGER_PDM_TR_ACTIVATE0 = 67, //!< TCPWM and PDM trigger multiplexer - pdm.tr_activate[0]
    CYHAL_TRIGGER_PDM_TR_ACTIVATE1 = 68, //!< TCPWM and PDM trigger multiplexer - pdm.tr_activate[1]
    CYHAL_TRIGGER_PDM_TR_ACTIVATE2 = 69, //!< TCPWM and PDM trigger multiplexer - pdm.tr_activate[2]
    CYHAL_TRIGGER_PDM_TR_ACTIVATE3 = 70, //!< TCPWM and PDM trigger multiplexer - pdm.tr_activate[3]
    CYHAL_TRIGGER_PDM_TR_DBG_FREEZE = 71, //!< PERI Freeze trigger multiplexer - pdm.tr_dbg_freeze
    CYHAL_TRIGGER_PERI_TR_DBG_FREEZE = 72, //!< PERI Freeze trigger multiplexer - peri.tr_dbg_freeze
    CYHAL_TRIGGER_PROFILE_TR_START = 73, //!< CPUSS Debug and Profiler trigger multiplexer - profile.tr_start
    CYHAL_TRIGGER_PROFILE_TR_STOP = 74, //!< CPUSS Debug and Profiler trigger multiplexer - profile.tr_stop
    CYHAL_TRIGGER_SRSS_TR_DEBUG_FREEZE_MCWDT0 = 75, //!< CPUSS Debug and Profiler trigger multiplexer - srss.tr_debug_freeze_mcwdt[0]
    CYHAL_TRIGGER_SRSS_TR_DEBUG_FREEZE_MCWDT1 = 76, //!< CPUSS Debug and Profiler trigger multiplexer - srss.tr_debug_freeze_mcwdt[1]
    CYHAL_TRIGGER_SRSS_TR_DEBUG_FREEZE_WDT = 77, //!< CPUSS Debug and Profiler trigger multiplexer - srss.tr_debug_freeze_wdt
    CYHAL_TRIGGER_TCPWM0_TR_IN0 = 78, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[0]
    CYHAL_TRIGGER_TCPWM0_TR_IN1 = 79, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[1]
    CYHAL_TRIGGER_TCPWM0_TR_IN2 = 80, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[2]
    CYHAL_TRIGGER_TCPWM0_TR_IN3 = 81, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[3]
    CYHAL_TRIGGER_TCPWM0_TR_IN4 = 82, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[4]
    CYHAL_TRIGGER_TCPWM0_TR_IN5 = 83, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[5]
    CYHAL_TRIGGER_TCPWM0_TR_IN6 = 84, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[6]
    CYHAL_TRIGGER_TCPWM0_TR_IN7 = 85, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[7]
    CYHAL_TRIGGER_TCPWM0_TR_IN8 = 86, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[8]
    CYHAL_TRIGGER_TCPWM0_TR_IN9 = 87, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[9]
    CYHAL_TRIGGER_TCPWM0_TR_IN10 = 88, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[10]
    CYHAL_TRIGGER_TCPWM0_TR_IN11 = 89, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[11]
    CYHAL_TRIGGER_TCPWM0_TR_IN12 = 90, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[12]
    CYHAL_TRIGGER_TCPWM0_TR_IN13 = 91, //!< TCPWM0 trigger multiplexer - tcpwm[0].tr_in[13]
    CYHAL_TRIGGER_TCPWM1_TR_IN0 = 92, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[0]
    CYHAL_TRIGGER_TCPWM1_TR_IN1 = 93, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[1]
    CYHAL_TRIGGER_TCPWM1_TR_IN2 = 94, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[2]
    CYHAL_TRIGGER_TCPWM1_TR_IN3 = 95, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[3]
    CYHAL_TRIGGER_TCPWM1_TR_IN4 = 96, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[4]
    CYHAL_TRIGGER_TCPWM1_TR_IN5 = 97, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[5]
    CYHAL_TRIGGER_TCPWM1_TR_IN6 = 98, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[6]
    CYHAL_TRIGGER_TCPWM1_TR_IN7 = 99, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[7]
    CYHAL_TRIGGER_TCPWM1_TR_IN8 = 100, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[8]
    CYHAL_TRIGGER_TCPWM1_TR_IN9 = 101, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[9]
    CYHAL_TRIGGER_TCPWM1_TR_IN10 = 102, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[10]
    CYHAL_TRIGGER_TCPWM1_TR_IN11 = 103, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[11]
    CYHAL_TRIGGER_TCPWM1_TR_IN12 = 104, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[12]
    CYHAL_TRIGGER_TCPWM1_TR_IN13 = 105, //!< TCPWM1 trigger multiplexer - tcpwm[1].tr_in[13]
    CYHAL_TRIGGER_TDM_TR_DBG_FREEZE = 106, //!< PERI Freeze trigger multiplexer - tdm.tr_dbg_freeze
} cyhal_trigger_dest_mxs28playermcuss_t;

/** Typedef from device family specific trigger dest to generic trigger dest */
typedef cyhal_trigger_dest_mxs28playermcuss_t cyhal_dest_t;

/** \cond INTERNAL */
/** Table of number of inputs to each mux. */
extern const uint16_t cyhal_sources_per_mux[15];

/** Table indicating whether mux is 1to1. */
extern const bool cyhal_is_mux_1to1[15];

/** Table pointing to each mux source table. The index of each source in the table is its mux input index. */
extern const _cyhal_trigger_source_mxs28playermcuss_t* cyhal_mux_to_sources [15];

/** Maps each cyhal_destination_t to a mux index.
 * If bit 8 of the mux index is set, this denotes that the trigger is a
 * one to one trigger.
 */
extern const uint8_t cyhal_dest_to_mux[107];

/* Maps each cyhal_destination_t to a specific output in its mux */
extern const uint8_t cyhal_mux_dest_index[107];
/** \endcond */

#if defined(__cplusplus)
}
#endif /* __cplusplus */
/** \} group_hal_impl_triggers_mxs28playermcuss */
#endif /* _CYHAL_TRIGGERS_MXS28PLAYERMCUSS_H_ */


/* [] END OF FILE */
