/***************************************************************************//**
* \file cyhal_triggers_mxs28playermcuss.c
*
* \brief
* MXS28PLAYERMCUSS family HAL triggers header
*
* \note
* Generator version: 1.6.0.512
*
********************************************************************************
* \copyright
* Copyright 2016-2021 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cy_device_headers.h"
#include "cyhal_hw_types.h"

#ifdef CY_DEVICE_MXS28PLAYERMCUSS
#include "triggers/cyhal_triggers_mxs28playermcuss.h"

const uint16_t cyhal_sources_per_mux[15] =
{
    97, 96, 164, 164, 226, 254, 63, 3, 61, 61, 13, 4, 2, 6, 9, 
};

const bool cyhal_is_mux_1to1[15] =
{
    false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, 
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux0_sources[97] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP2,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ1,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ3,
    _CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_FROM_WLAN_OUT,
    _CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux1_sources[96] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP2,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ1,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ3,
    _CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_FROM_WLAN_OUT,
    _CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux2_sources[164] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT1,
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB6_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB6_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB6_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB7_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_RX_REQ,
    _CYHAL_TRIGGER_I3C_TR_TX_REQ,
    _CYHAL_TRIGGER_I3C_TR_RX_REQ,
    _CYHAL_TRIGGER_ADCCOMP_TR_CIC,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ_ALL,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_SMIF_TR_TX_REQ,
    _CYHAL_TRIGGER_SMIF_TR_RX_REQ,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ1,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ3,
    _CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_FROM_WLAN_OUT,
    _CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux3_sources[164] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT1,
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB6_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB6_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB6_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB7_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_RX_REQ,
    _CYHAL_TRIGGER_I3C_TR_TX_REQ,
    _CYHAL_TRIGGER_I3C_TR_RX_REQ,
    _CYHAL_TRIGGER_ADCCOMP_TR_CIC,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ_ALL,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_SMIF_TR_TX_REQ,
    _CYHAL_TRIGGER_SMIF_TR_RX_REQ,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ1,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ3,
    _CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_FROM_WLAN_OUT,
    _CYHAL_TRIGGER_ETH0_ETH_TSU_TIMER_CMP_VAL_OUT,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux4_sources[226] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT15,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT16,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT17,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT18,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT19,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT20,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT21,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT22,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT23,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT24,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT25,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT26,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT27,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT28,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT15,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT16,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT17,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT18,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT19,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT20,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT21,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT22,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT23,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT24,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT25,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT26,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT27,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT28,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT1,
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB6_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB6_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB6_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB7_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_RX_REQ,
    _CYHAL_TRIGGER_I3C_TR_TX_REQ,
    _CYHAL_TRIGGER_I3C_TR_RX_REQ,
    _CYHAL_TRIGGER_ADCCOMP_TR_CIC,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ_ALL,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ1,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ3,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux5_sources[254] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT15,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT16,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT17,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT18,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT19,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT20,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT21,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT22,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT23,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT24,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT25,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT26,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT27,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT28,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT15,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT16,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT17,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT18,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT19,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT20,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT21,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT22,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT23,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT24,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT25,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT26,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT27,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT28,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DMAC1_TR_OUT1,
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB6_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB6_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB6_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB7_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_RX_REQ,
    _CYHAL_TRIGGER_I3C_TR_TX_REQ,
    _CYHAL_TRIGGER_I3C_TR_RX_REQ,
    _CYHAL_TRIGGER_ADCCOMP_TR_CIC,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ_ALL,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_SMIF_TR_TX_REQ,
    _CYHAL_TRIGGER_SMIF_TR_RX_REQ,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ1,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP1,
    _CYHAL_TRIGGER_ADCCOMP_TR_LPCOMP2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ3,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux6_sources[63] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7,
    _CYHAL_TRIGGER_SMIF_TR_TX_REQ,
    _CYHAL_TRIGGER_SMIF_TR_RX_REQ,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux7_sources[3] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_CTI_TR_OUT1,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux8_sources[61] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux9_sources[61] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM0_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM0_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM0_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH0,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW0,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH1,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW1,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH2,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW2,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH3,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW3,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH4,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW4,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH5,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW5,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH6,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW6,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH7,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW7,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH8,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW8,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH9,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW9,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH10,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW10,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH11,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW11,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH12,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW12,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH13,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW13,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH14,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW14,
    _CYHAL_TRIGGER_TCPWM1_TR_OVERFLOW15,
    _CYHAL_TRIGGER_TCPWM1_TR_CC_MATCH15,
    _CYHAL_TRIGGER_TCPWM1_TR_UNDERFLOW15,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux10_sources[13] =
{
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_CPUSS_ZERO,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux11_sources[4] =
{
    _CYHAL_TRIGGER_SCB6_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB6_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB7_TR_RX_REQ,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux12_sources[2] =
{
    _CYHAL_TRIGGER_SMIF_TR_TX_REQ,
    _CYHAL_TRIGGER_SMIF_TR_RX_REQ,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux13_sources[6] =
{
    _CYHAL_TRIGGER_TDM_TR_TX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ0,
    _CYHAL_TRIGGER_TDM_TR_TX_REQ1,
    _CYHAL_TRIGGER_TDM_TR_RX_REQ1,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ1,
};

const _cyhal_trigger_source_mxs28playermcuss_t cyhal_mux14_sources[9] =
{
    _CYHAL_TRIGGER_PDM_TR_RX_REQ2,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ3,
    _CYHAL_TRIGGER_I3C_TR_TX_REQ,
    _CYHAL_TRIGGER_I3C_TR_RX_REQ,
    _CYHAL_TRIGGER_ADCCOMP_TR_CIC,
    _CYHAL_TRIGGER_PDM_TR_RX_REQ_ALL,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_ZERO,
};

const _cyhal_trigger_source_mxs28playermcuss_t* cyhal_mux_to_sources[15] =
{
    cyhal_mux0_sources, 
    cyhal_mux1_sources, 
    cyhal_mux2_sources, 
    cyhal_mux3_sources, 
    cyhal_mux4_sources, 
    cyhal_mux5_sources, 
    cyhal_mux6_sources, 
    cyhal_mux7_sources, 
    cyhal_mux8_sources, 
    cyhal_mux9_sources, 
    cyhal_mux10_sources, 
    cyhal_mux11_sources, 
    cyhal_mux12_sources, 
    cyhal_mux13_sources, 
    cyhal_mux14_sources, 
};

const uint8_t cyhal_dest_to_mux[107] =
{
    9, /* CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_TO_WLAN_IN */
    5, /* CYHAL_TRIGGER_CPUSS_CTI_TR_IN0 */
    5, /* CYHAL_TRIGGER_CPUSS_CTI_TR_IN1 */
    6, /* CYHAL_TRIGGER_CPUSS_DMAC0_TR_IN0 */
    6, /* CYHAL_TRIGGER_CPUSS_DMAC0_TR_IN1 */
    6, /* CYHAL_TRIGGER_CPUSS_DMAC1_TR_IN0 */
    6, /* CYHAL_TRIGGER_CPUSS_DMAC1_TR_IN1 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN0 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN1 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN2 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN3 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN4 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN5 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN6 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN7 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN8 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN9 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN10 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN11 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN12 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN13 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN14 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN15 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN16 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN17 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN18 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN19 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN20 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN21 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN22 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN23 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN24 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN25 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN26 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN27 */
    128, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN28 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN0 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN1 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN2 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN3 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN4 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN5 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN6 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN7 */
    129, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN8 */
    129, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN9 */
    129, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN10 */
    129, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN11 */
    130, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN12 */
    130, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN13 */
    131, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN14 */
    131, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN15 */
    131, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN16 */
    131, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN17 */
    131, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN18 */
    131, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN19 */
    132, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN20 */
    132, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN21 */
    132, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN22 */
    132, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN23 */
    132, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN24 */
    132, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN25 */
    132, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN26 */
    132, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN27 */
    132, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN28 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT0 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT1 */
    8, /* CYHAL_TRIGGER_PDM_TR_ACTIVATE0 */
    8, /* CYHAL_TRIGGER_PDM_TR_ACTIVATE1 */
    8, /* CYHAL_TRIGGER_PDM_TR_ACTIVATE2 */
    8, /* CYHAL_TRIGGER_PDM_TR_ACTIVATE3 */
    7, /* CYHAL_TRIGGER_PDM_TR_DBG_FREEZE */
    7, /* CYHAL_TRIGGER_PERI_TR_DBG_FREEZE */
    5, /* CYHAL_TRIGGER_PROFILE_TR_START */
    5, /* CYHAL_TRIGGER_PROFILE_TR_STOP */
    5, /* CYHAL_TRIGGER_SRSS_TR_DEBUG_FREEZE_MCWDT0 */
    5, /* CYHAL_TRIGGER_SRSS_TR_DEBUG_FREEZE_MCWDT1 */
    5, /* CYHAL_TRIGGER_SRSS_TR_DEBUG_FREEZE_WDT */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN0 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN1 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN2 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN3 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN4 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN5 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN6 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN7 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN8 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN9 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN10 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN11 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN12 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN13 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN0 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN1 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN2 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN3 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN4 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN5 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN6 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN7 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN8 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN9 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN10 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN11 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN12 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN13 */
    7, /* CYHAL_TRIGGER_TDM_TR_DBG_FREEZE */
};

const uint8_t cyhal_mux_dest_index[107] =
{
    0, /* CYHAL_TRIGGER_CONNBRIDGE_TCPWM_TRIG_TO_WLAN_IN */
    0, /* CYHAL_TRIGGER_CPUSS_CTI_TR_IN0 */
    1, /* CYHAL_TRIGGER_CPUSS_CTI_TR_IN1 */
    0, /* CYHAL_TRIGGER_CPUSS_DMAC0_TR_IN0 */
    1, /* CYHAL_TRIGGER_CPUSS_DMAC0_TR_IN1 */
    2, /* CYHAL_TRIGGER_CPUSS_DMAC1_TR_IN0 */
    3, /* CYHAL_TRIGGER_CPUSS_DMAC1_TR_IN1 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN0 */
    1, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN1 */
    2, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN2 */
    3, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN3 */
    4, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN4 */
    5, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN5 */
    6, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN6 */
    7, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN7 */
    8, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN8 */
    9, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN9 */
    10, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN10 */
    11, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN11 */
    12, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN12 */
    13, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN13 */
    14, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN14 */
    15, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN15 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN16 */
    1, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN17 */
    2, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN18 */
    3, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN19 */
    4, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN20 */
    5, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN21 */
    6, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN22 */
    7, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN23 */
    8, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN24 */
    9, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN25 */
    10, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN26 */
    11, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN27 */
    12, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN28 */
    0, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN0 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN1 */
    2, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN2 */
    3, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN3 */
    4, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN4 */
    5, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN5 */
    6, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN6 */
    7, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN7 */
    0, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN8 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN9 */
    2, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN10 */
    3, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN11 */
    0, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN12 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN13 */
    0, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN14 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN15 */
    2, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN16 */
    3, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN17 */
    4, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN18 */
    5, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN19 */
    0, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN20 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN21 */
    2, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN22 */
    3, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN23 */
    4, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN24 */
    5, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN25 */
    6, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN26 */
    7, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN27 */
    8, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN28 */
    0, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT0 */
    1, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT1 */
    0, /* CYHAL_TRIGGER_PDM_TR_ACTIVATE0 */
    1, /* CYHAL_TRIGGER_PDM_TR_ACTIVATE1 */
    2, /* CYHAL_TRIGGER_PDM_TR_ACTIVATE2 */
    3, /* CYHAL_TRIGGER_PDM_TR_ACTIVATE3 */
    1, /* CYHAL_TRIGGER_PDM_TR_DBG_FREEZE */
    0, /* CYHAL_TRIGGER_PERI_TR_DBG_FREEZE */
    2, /* CYHAL_TRIGGER_PROFILE_TR_START */
    3, /* CYHAL_TRIGGER_PROFILE_TR_STOP */
    5, /* CYHAL_TRIGGER_SRSS_TR_DEBUG_FREEZE_MCWDT0 */
    6, /* CYHAL_TRIGGER_SRSS_TR_DEBUG_FREEZE_MCWDT1 */
    4, /* CYHAL_TRIGGER_SRSS_TR_DEBUG_FREEZE_WDT */
    0, /* CYHAL_TRIGGER_TCPWM0_TR_IN0 */
    1, /* CYHAL_TRIGGER_TCPWM0_TR_IN1 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_IN2 */
    3, /* CYHAL_TRIGGER_TCPWM0_TR_IN3 */
    4, /* CYHAL_TRIGGER_TCPWM0_TR_IN4 */
    5, /* CYHAL_TRIGGER_TCPWM0_TR_IN5 */
    6, /* CYHAL_TRIGGER_TCPWM0_TR_IN6 */
    7, /* CYHAL_TRIGGER_TCPWM0_TR_IN7 */
    8, /* CYHAL_TRIGGER_TCPWM0_TR_IN8 */
    9, /* CYHAL_TRIGGER_TCPWM0_TR_IN9 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_IN10 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_IN11 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_IN12 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_IN13 */
    0, /* CYHAL_TRIGGER_TCPWM1_TR_IN0 */
    1, /* CYHAL_TRIGGER_TCPWM1_TR_IN1 */
    2, /* CYHAL_TRIGGER_TCPWM1_TR_IN2 */
    3, /* CYHAL_TRIGGER_TCPWM1_TR_IN3 */
    4, /* CYHAL_TRIGGER_TCPWM1_TR_IN4 */
    5, /* CYHAL_TRIGGER_TCPWM1_TR_IN5 */
    6, /* CYHAL_TRIGGER_TCPWM1_TR_IN6 */
    7, /* CYHAL_TRIGGER_TCPWM1_TR_IN7 */
    8, /* CYHAL_TRIGGER_TCPWM1_TR_IN8 */
    9, /* CYHAL_TRIGGER_TCPWM1_TR_IN9 */
    10, /* CYHAL_TRIGGER_TCPWM1_TR_IN10 */
    11, /* CYHAL_TRIGGER_TCPWM1_TR_IN11 */
    12, /* CYHAL_TRIGGER_TCPWM1_TR_IN12 */
    13, /* CYHAL_TRIGGER_TCPWM1_TR_IN13 */
    2, /* CYHAL_TRIGGER_TDM_TR_DBG_FREEZE */
};

#endif /* CY_DEVICE_MXS28PLAYERMCUSS */
